"""
Integration module for My-IDM Download Manager (D:\\Projects\\my-idm).
Manages appending download URLs to My-IDM backlog files and launching the application.
"""

from __future__ import annotations

import os
import sys
import subprocess
from pathlib import Path
from typing import Optional, Tuple, List, Dict, Any

import config
from .utils import log_debug

_pending_download_count: int = 0
_backlog_entries: List[Dict[str, Any]] = []


def reset_pending_download_count() -> None:
    global _pending_download_count
    _pending_download_count = 0


def get_pending_download_count() -> int:
    return _pending_download_count


def _increment_pending_downloads() -> None:
    global _pending_download_count
    _pending_download_count += 1


def reset_backlog_entries() -> None:
    """Clear the collected backlog entries."""
    global _backlog_entries
    _backlog_entries = []


def get_backlog_entries() -> List[Dict[str, Any]]:
    """Get the collected backlog entries."""
    return _backlog_entries


def add_backlog_entry(
    url: str,
    filename: Optional[str] = None,
    title: Optional[str] = None,
    ep_num: Optional[int] = None,
    save_path: Optional[str] = None,
    queue: Optional[str] = None,
    anime_url: Optional[str] = None,
) -> None:
    """
    Collect a backlog entry to be written later in batch.
    
    Args:
        url: Direct download URL
        filename: Target filename
        title: Anime title
        ep_num: Episode number
        save_path: Save directory
        queue: Queue name
        anime_url: AnimePahe anime URL (for reference in details panel)
    """
    clean_url = url.strip()
    if not clean_url:
        return

    comment = "# AnimePahe Download"
    if title and ep_num is not None:
        comment = f"# {title} - Episode {ep_num}"
    elif title:
        comment = f"# {title}"
    if filename:
        comment += f" ({filename})"

    clean_save_path = save_path.strip() if save_path else None
    clean_filename = filename.strip() if filename else None
    if clean_save_path and clean_filename:
        entry_line = f"{clean_url} | {clean_save_path} | {clean_filename}"
    elif clean_save_path:
        entry_line = f"{clean_url} | {clean_save_path}"
    elif clean_filename:
        entry_line = f"{clean_url} | filename={clean_filename}"
    else:
        entry_line = clean_url

    if queue is None:
        queue = getattr(config, "MY_IDM_QUEUE_NAME", "")
    queue_name = queue.strip() if queue else ""
    if queue_name:
        entry_line += f" | queue={queue_name}"

    # Add anime_url and anime_title as custom key=value pairs for my-idm to parse into metadata
    if anime_url:
        entry_line += f" | anime_url={anime_url}"
    if title:
        entry_line += f" | anime_title={title}"

    # Store in meta for reference
    meta: Dict[str, Any] = {}
    if anime_url:
        meta["anime_url"] = anime_url
    if title:
        meta["anime_title"] = title
    if ep_num is not None:
        meta["episode_num"] = ep_num

    _backlog_entries.append({
        "url": clean_url,
        "entry_line": entry_line,
        "comment": comment,
        "meta": meta,
    })


def write_backlog_entries() -> bool:
    """
    Write all collected backlog entries to the backlog file(s) at once.
    Returns True if any entries were added.
    """
    global _backlog_entries
    if not _backlog_entries:
        return False

    backlog_path = get_my_idm_backlog_path()
    app_backlog_path = get_default_app_backlog_path()

    added_any = False
    for target_path in [backlog_path, app_backlog_path]:
        try:
            parent_dir = os.path.dirname(target_path)
            if parent_dir and not os.path.exists(parent_dir):
                os.makedirs(parent_dir, exist_ok=True)

            # Read existing URLs for deduplication
            existing_urls = set()
            if os.path.exists(target_path):
                with open(target_path, "r", encoding="utf-8", errors="replace") as f:
                    for line in f:
                        line_clean = line.strip()
                        if not line_clean or line_clean.startswith("#") or line_clean.startswith("//"):
                            continue
                        line_url = line_clean.split("|")[0].split("->")[0].strip()
                        if " dir=" in line_url.lower():
                            line_url = line_url.split(" dir=")[0].split(" DIR=")[0].strip()
                        existing_urls.add(line_url)

            # Write new entries
            is_new_file = not os.path.exists(target_path) or os.path.getsize(target_path) == 0
            with open(target_path, "a", encoding="utf-8") as f:
                if is_new_file:
                    f.write("# My-IDM Backlog File - Generated by AnimePahe Downloader\n")
                for entry in _backlog_entries:
                    if entry["url"] not in existing_urls:
                        f.write(f"\n{entry['comment']}\n{entry['entry_line']}\n")
                        existing_urls.add(entry["url"])
                        added_any = True
                        log_debug(f"Added URL to backlog {target_path}: {entry['comment']} -> {entry['entry_line']}")
                    else:
                        log_debug(f"URL already in backlog {target_path}: {entry['url']}")
        except Exception as exc:
            log_debug(f"Failed writing to backlog {target_path}: {exc}")

    if added_any:
        _increment_pending_downloads()

    # Clear entries after writing
    _backlog_entries = []
    return added_any


def get_my_idm_dir() -> str:
    """Return configured or default My-IDM repository directory."""
    raw_dir = getattr(config, "MY_IDM_DIR", r"D:\Projects\my-idm")
    return os.path.abspath(raw_dir)


def get_my_idm_backlog_path() -> str:
    """Return target backlog file path in My-IDM."""
    custom_path = getattr(config, "MY_IDM_BACKLOG_FILE", "")
    if custom_path and str(custom_path).strip():
        return os.path.abspath(str(custom_path).strip())
    return os.path.join(get_my_idm_dir(), "backlog.txt")


def get_default_app_backlog_path() -> str:
    """Return standard user home backlog path (~/.my-idm/backlog.txt)."""
    return str(Path.home() / ".my-idm" / "backlog.txt")


def add_to_my_idm_backlog(
    url: str,
    filename: Optional[str] = None,
    title: Optional[str] = None,
    ep_num: Optional[int] = None,
    save_path: Optional[str] = None,
    queue: Optional[str] = None,
) -> bool:
    """
    Append a direct download URL and metadata comment to the My-IDM backlog file.
    Supports inline custom download location delimiter: 'url | save_path'.
    Also synchronizes to ~/.my-idm/backlog.txt so My-IDM can read it without CLI args.

    ``queue`` names the My-IDM queue the entry belongs to, written as a trailing
    ``| queue=<name>`` column. Defaults to ``config.MY_IDM_QUEUE_NAME``; pass "" to omit the
    column entirely. My-IDM resolves the name case-insensitively and falls back to its Default
    queue for a name it does not know, so this is safe to leave set even if the queue is
    renamed or removed there.

    Returns True if the URL was added, False if it was already present.
    """
    # Use the new batch mechanism internally
    add_backlog_entry(url, filename=filename, title=title, ep_num=ep_num, save_path=save_path, queue=queue)
    # For backwards compatibility, write immediately (but this can be batched by caller)
    return write_backlog_entries()


def is_my_idm_running() -> bool:
    """Check if an instance of My-IDM is currently running on the system."""
    current_pid = os.getpid()
    try:
        import psutil
        for proc in psutil.process_iter(attrs=["pid", "name", "cmdline"]):
            if proc.info.get("pid") == current_pid:
                continue
            proc_name = (proc.info.get("name") or "").lower()
            if not proc_name.startswith("python"):
                continue

            cmdline = proc.info.get("cmdline") or []
            if len(cmdline) < 2:
                continue

            full_cmd = " ".join(cmdline).replace("\\", "/").lower()
            for i, arg in enumerate(cmdline[1:], start=1):
                norm_arg = arg.replace("\\", "/").lower()
                if (
                    norm_arg in ("my_idm", "my_idm.main")
                    or norm_arg.endswith("/my_idm/main.py")
                    or norm_arg.endswith("/my_idm/__main__.py")
                    or norm_arg.endswith("/my-idm/run.pyw")
                    or (norm_arg.endswith("run.pyw") and "my-idm" in full_cmd)
                ):
                    return True
                if norm_arg == "-m" and i < len(cmdline) - 1:
                    next_arg = cmdline[i + 1].lower()
                    if next_arg in ("my_idm", "my_idm.main") or next_arg.startswith("my_idm."):
                        return True
    except Exception as exc:
        log_debug(f"is_my_idm_running check error: {exc}")
    return False


def launch_my_idm(
    my_idm_dir: Optional[str] = None,
    backlog_file: Optional[str] = None,
    force: bool = False,
) -> Tuple[bool, str]:
    """
    Launch the My-IDM desktop application detached from the current process.
    Passes the backlog file argument so newly queued downloads are processed.
    """
    if my_idm_dir is None:
        my_idm_dir = get_my_idm_dir()
    if backlog_file is None:
        backlog_file = get_my_idm_backlog_path()

    if not os.path.isdir(my_idm_dir):
        return False, f"My-IDM directory does not exist: {my_idm_dir}"

    if not force and is_my_idm_running():
        return True, f"My-IDM is already running (backlog file: {backlog_file})"

    # Locate best executable and launchers
    run_pyw = os.path.join(my_idm_dir, "run.pyw")
    venv_pythonw = os.path.join(my_idm_dir, ".venv", "Scripts", "pythonw.exe")
    alt_venv_pythonw = os.path.join(my_idm_dir, "venv", "Scripts", "pythonw.exe")
    run_bat = os.path.join(my_idm_dir, "run.bat")

    pythonw_exe = sys.executable.replace("python.exe", "pythonw.exe")
    if not os.path.isfile(pythonw_exe):
        pythonw_exe = "pythonw"

    # Select pythonw interpreter
    if os.path.isfile(venv_pythonw):
        target_pythonw = venv_pythonw
    elif os.path.isfile(alt_venv_pythonw):
        target_pythonw = alt_venv_pythonw
    else:
        target_pythonw = pythonw_exe

    args = ["--backlog", backlog_file] if os.path.exists(backlog_file) else []

    try:
        flags = getattr(subprocess, "DETACHED_PROCESS", 0x00000008) | getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0x00000200)

        # 1. Prioritize console-less run.pyw launcher (equivalent to: start "" pythonw run.pyw)
        if os.path.isfile(run_pyw):
            cmd = [target_pythonw, run_pyw] + args
            subprocess.Popen(
                cmd,
                cwd=my_idm_dir,
                creationflags=flags,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                close_fds=True,
            )
            return True, f"Launched My-IDM console-less via pythonw run.pyw from {my_idm_dir}"

        elif os.path.isfile(venv_pythonw):
            cmd = [venv_pythonw, "-m", "my_idm.main"] + args
            subprocess.Popen(cmd, cwd=my_idm_dir, creationflags=flags, stdin=subprocess.DEVNULL)
            return True, f"Launched My-IDM via virtualenv pythonw from {my_idm_dir}"

        elif os.path.isfile(alt_venv_pythonw):
            cmd = [alt_venv_pythonw, "-m", "my_idm.main"] + args
            subprocess.Popen(cmd, cwd=my_idm_dir, creationflags=flags, stdin=subprocess.DEVNULL)
            return True, f"Launched My-IDM via venv pythonw from {my_idm_dir}"

        elif os.path.isfile(pythonw_exe):
            cmd = [pythonw_exe, "-m", "my_idm.main"] + args
            subprocess.Popen(cmd, cwd=my_idm_dir, creationflags=flags, stdin=subprocess.DEVNULL)
            return True, f"Launched My-IDM via pythonw from {my_idm_dir}"

        elif os.path.isfile(run_bat):
            cmd = f'cmd.exe /c start "" /D "{my_idm_dir}" "{run_bat}" ' + " ".join(f'"{a}"' for a in args)
            subprocess.Popen(cmd, shell=True, cwd=my_idm_dir)
            return True, f"Launched My-IDM via run.bat from {my_idm_dir}"

        else:
            # Fallback to sys.executable
            cmd = [sys.executable, "-m", "my_idm.main"] + args
            subprocess.Popen(cmd, cwd=my_idm_dir, creationflags=flags, stdin=subprocess.DEVNULL)
            return True, f"Launched My-IDM via python from {my_idm_dir}"

    except Exception as exc:
        log_debug(f"Failed to launch My-IDM: {exc}")
        return False, f"Failed to launch My-IDM: {exc}"
